const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getPresets: () => ipcRenderer.invoke('net:getPresets'),
  getGamePresets: () => ipcRenderer.invoke('games:getPresets'),
  startMonitor: (host, gameId) => ipcRenderer.invoke('net:startMonitor', { host, gameId }),
  stopMonitor: () => ipcRenderer.invoke('net:stopMonitor'),
  onSample: (cb) => ipcRenderer.on('net:sample', (event, data) => cb(data)),
  onProgress: (cb) => ipcRenderer.on('net:progress', (event, data) => cb(data)),
  onComplete: (cb) => ipcRenderer.on('net:complete', () => cb()),
  onOverlayReset: (cb) => ipcRenderer.on('net:reset', () => cb()),
  onAlert: (cb) => ipcRenderer.on('net:alert', (event, data) => cb(data)),
  getSessions: () => ipcRenderer.invoke('history:getSessions'),
  deleteSession: (sessionId) => ipcRenderer.invoke('history:deleteSession', sessionId),
  clearHistory: () => ipcRenderer.invoke('history:clear'),
  exportHistory: (format, data) => ipcRenderer.invoke('history:export', { format, data }),
  getGameProcesses: () => ipcRenderer.invoke('sys:getGameProcesses'),
  getConnection: () => ipcRenderer.invoke('sys:getConnection'),
  traceroute: (host) => ipcRenderer.invoke('diag:traceroute', host),
  traceDetailed: (host) => ipcRenderer.invoke('diag:traceDetailed', host),
  speedtest: () => ipcRenderer.invoke('diag:speedtest'),
  cancelSpeedtest: () => ipcRenderer.invoke('diag:speedtestCancel'),
  onSpeedtestProgress: (cb) => ipcRenderer.on('diag:speedtestProgress', (event, data) => cb(data)),
  fullTest: (host) => ipcRenderer.invoke('diag:fullTest', host),
  onFullTestProgress: (cb) => ipcRenderer.on('diag:fullTestProgress', (event, data) => cb(data)),
  benchmarkRegions: (gameId) => ipcRenderer.invoke('games:benchmarkRegions', gameId),
  getAutostart: () => ipcRenderer.invoke('app:getAutostart'),
  setAutostart: (enabled) => ipcRenderer.invoke('app:setAutostart', enabled),
  getAppInfo: () => ipcRenderer.invoke('app:getInfo'),
  checkForUpdates: () => ipcRenderer.invoke('app:checkForUpdates'),
  downloadUpdate: () => ipcRenderer.invoke('app:downloadUpdate'),
  installUpdate: () => ipcRenderer.invoke('app:installUpdate'),
  onUpdateStatus: (cb) => ipcRenderer.on('app:updateStatus', (event, data) => cb(data)),
  exportLogs: () => ipcRenderer.invoke('app:exportLogs'),
  gameMode: (gameId) => ipcRenderer.invoke('boost:gameMode', gameId),
  windowMinimize: () => ipcRenderer.invoke('window:minimize'),
  windowClose: () => ipcRenderer.invoke('window:close'),
  openDiscord: () => ipcRenderer.invoke('app:openDiscord'),
  restartAsAdmin: () => ipcRenderer.invoke('app:restartAsAdmin'),

  getSnapshot: () => ipcRenderer.invoke('sys:getSnapshot'),
  killProcess: (pid) => ipcRenderer.invoke('boost:killProcess', pid),
  setHighPriority: (pid) => ipcRenderer.invoke('boost:setHighPriority', pid),
  highPerfPowerPlan: () => ipcRenderer.invoke('boost:highPerfPowerPlan'),
  flushDns: () => ipcRenderer.invoke('boost:flushDns'),
  tcpOptimize: () => ipcRenderer.invoke('boost:tcpOptimize'),
  applyBoostOption: (option, enabled) => ipcRenderer.invoke('boost:applyOption', { option, enabled }),
  undoBoostOption: (option) => ipcRenderer.invoke('boost:undoOption', option),
  getBoostChanges: () => ipcRenderer.invoke('boost:getChanges'),
  cleanMemory: (exclusions) => ipcRenderer.invoke('boost:cleanMemory', exclusions),
  backupBoostSettings: () => ipcRenderer.invoke('boost:backupSettings'),
  restoreBoostSettings: () => ipcRenderer.invoke('boost:restoreSettings'),
  toggleOverlay: () => ipcRenderer.invoke('overlay:toggle'),
  getOverlayPing: () => ipcRenderer.invoke('overlay:ping'),
});
